### ISSUE TITLE
Provide the way to use or run rsp-server in debug mode

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-server-connector#177]
Some problems on RSP server side would be required to use remote java debugger, so we should provide the way to force extension to sart server in debug mode.

**Comment by robstryker** [comment]
Care to explain more, or make a linked issue in rsp-server?  My understanding is that we have all the required APIs to start in debug mode. Let me know if any specific use case doesn't work?

**Comment by adietish** [comment]
moving to `devex #163`

**Comment by lstocchi** [comment]
duplicate? #126  ... Already working on it

**Comment by jeffmaury** [comment]
No it's not about the same. #126 is about running a server in debug mode, this one is about running rsp-server is debug mode so that we call follow the workflow is rsp-server.
I would suggest that we run rsp-server is debug mode from an Eclipse workspace and through an environment variable that would store the rsp-server port, we just connect to this rsp-server instead of launching rsp-server the connecting to it.

**Comment by robstryker** [comment]
There are ways to debug rsp-server now. I don't think this is an issue we should solve by exposing the option to the user. THis is clearly a development-time issue and not one for user consumption. So I prefer to use other methods like launching via eclipse or via cmd-line directly when debugging issues.
