### ISSUE TITLE
investigate ways to present forms when user needs to provide multiple inputs

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-server-connector#210]
https://marketplace.visualstudio.com/items?itemName=anseki.vscode-color is using electron to present a color picker in a vscode editor. We're looking into how we could leverage similar means.
The code is at https://github.com/anseki/vscode-color
Related to this is the webview which can be displayed in vscode: https://code.visualstudio.com/api/extension-guides/webview

**Comment by adietish** [comment]
removed devex #161, postponed to later

**Comment by robstryker** [comment]
The latest idea was to consider  https://code.visualstudio.com/api/extension-guides/webview   webviews instead of electron. Webviews come as a supported API.

**Comment by lstocchi** [comment]
I investigate a little bit on the color-picker extension and vscode webview. There were any reasons why you were considering webviews instead of electron? @adietish @robstryker 

Even though they both are far from offering an optimal solution, electron has one big plus - being able to display a form outside of a tab and (i guess) give the chance to position it wherever we want. 
![color-picker](https://user-images.githubusercontent.com/49404737/57631935-ba295980-75a0-11e9-8157-ddb94a646532.png)
It's a completely independent page so you can show an advanced form to the user.

I am still not sure if we can accomplish something useful with it but it seems more powerful than webviews.

**Comment by robstryker** [comment]
https://github.com/redhat-developer/vscode-rsp-ui/commit/86b3e54fe4c40ebd9400c32cccec36705afe9a82

Webview implementation chosen. So far only available for create new server, not available for download runtime
