### ISSUE TITLE
Startup Script JAVA_OPTS beieng ignored

### ISSUE THREAD

**Issue by Somebody25** [redhat-developer/vscode-server-connector#375]
Hello!

I have a relatively large project that needs more RAM than is default with wildfly. To do this, I changed the JAVA_OPTS parameters in the /bin/standalone.conf.bat file of the wildfly from:
`set "JAVA_OPTS=-Xms64M -Xmx512M -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m"`
to:
`set "JAVA_OPTS=-Xms512M -Xmx2g -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m"`

This does work if I start the wildfly manually by executing the standalone.bat in a terminal. The extension, however, seems to ignore this setting because the server is dying with a GC overhead limit exceeded when I try it there.

Thanks for the help!

depends on https://github.com/redhat-developer/rsp-server/issues/422

**Comment by adietish** [comment]
@Somebody25 thx for creating this.
Once we created the backend portion at https://github.com/redhat-developer/rsp-server/issues/422 we'll have to provide JAVA_OPTS editing capabilities here in the frontend.

**Comment by robstryker** [comment]
I think this issue is fixed. We don't allow you to run via the shell script /.bat file. But we do provide methods for you to override or customize various program and vm arguments. See this video for more information:   https://www.youtube.com/watch?v=sP2Hlw-C_7I

You might prefer to skip right to the 'editing the server' part:  https://youtu.be/sP2Hlw-C_7I?t=768
This shows you some of the keys or constants you can use to override the program or vm args in that json representation of your server adapter.
