### ISSUE TITLE
Cannot create CRC adapter from local directory

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-server-connector#407]
1. Started RSP
2. Create new server
3. Use server on disk
4. Choose path with downloaded and extracted crc.
5. Choose pull secret file
6. ASSERT: New server is created
Actually when I choose folder with crc binary I got backend error:
```
Unable to create the server:  Extension backend error - could not detect any server at /home/odockal/apps/crc/crc-linux-1.0.0-amd64!
```

and json messages from debug console are:
```
Message=Sending request 'server/findServerBeans - (85)'. data=Params: {
    "filepath": "/home/odockal/Apps/crc/crc-linux-1.1.0-amd64"
}


client.js:41
Message=Received response 'server/findServerBeans - (85)' in 52ms. data=Result: [
    {
        "location": "/home/odockal/Apps/crc/crc-linux-1.1.0-amd64",
        "typeCategory": "UNKNOWN",
        "name": "crc-linux-1.1.0-amd64",
        "version": ""
    }
]
```

**Comment by robstryker** [comment]
This is a broken use case due to changes upstream. They have changed the version key from "version" to "crc version", which is a breaking change for us. 

[rob@rawbeast crc-linux-1.1.0-amd64]$ ./crc version
crc version: 1.1.0+95966a9
OpenShift version: 4.2.2 (embedded in binary)

[rob@rawbeast crc-linux-1.0.0-beta.5-amd64]$ ./crc version
version: 1.0.0-beta.5+f2aa58c
OpenShift version: 4.1.14 (embedded in binary)

**Comment by odockal** [comment]
oh dear, I was fixing this in jbt. Has not this been already done in crc 1.0.0? Maybe? But anyway, it was one line fix, could be quite easy one.

**Comment by robstryker** [comment]
https://github.com/redhat-developer/rsp-server/pull/516
