### ISSUE TITLE
Connector for Jboss AS 4.2

### ISSUE THREAD

**Issue by Swe77** [redhat-developer/vscode-server-connector#428]
Hi!

Can you provide a connector for Jboss AS 4.2 please?

Swe77

**Comment by RogerioPST** [comment]
This will save me. 
I would like it too, please.
Tks

**Comment by robstryker** [comment]
We already have one. It's available in this extension. But there is an issue with using jboss 4.2, specifically, you need to set the appropriate java vm because JBoss 4.2 does not work with java 8.  And I just ran through and discovered that there's some bugs when trying to set the alternate VM.  I'll try to push out a change ASAP. 

But until then, here's the workflow just so you're aware of it. 

So you need to right-click the rsp provider in the view / activity tab, and then click create new server... and then 'No I'll use the one on disk" and browse to it.  After selecting the server home, it will ask for a name (you can provide anything, My JBoss 4.2 for example) and then it will ask if you want to override the optional settings. You should click 'yes' here. 

The first question should be for you to select a java home. You paste or type it in. The rest of the questions you can ignore. 

The other option is to use the download-server feature, select 4.2, and wait for it to complete. When complete, you will need to right-click the server and edit it, and add the following line to your server file:    "vm.install.path": "/path/to/your/jdk1.5.0_22/",

I'll work to get these bugs fixed.

**Comment by Swe77** [comment]
> We already have one. It's available in this extension. But there is an issue with using jboss 4.2, specifically, you need to set the appropriate java vm because JBoss 4.2 does not work with java 8. And I just ran through and discovered that there's some bugs when trying to set the alternate VM. I'll try to push out a change ASAP.
> 
> But until then, here's the workflow just so you're aware of it.
> 
> So you need to right-click the rsp provider in the view / activity tab, and then click create new server... and then 'No I'll use the one on disk" and browse to it. After selecting the server home, it will ask for a name (you can provide anything, My JBoss 4.2 for example) and then it will ask if you want to override the optional settings. You should click 'yes' here.
> 
> The first question should be for you to select a java home. You paste or type it in. The rest of the questions you can ignore.
> 
> The other option is to use the download-server feature, select 4.2, and wait for it to complete. When complete, you will need to right-click the server and edit it, and add the following line to your server file: "vm.install.path": "/path/to/your/jdk1.5.0_22/",
> 
> I'll work to get these bugs fixed.

Thank you, it will help me on the transition from eclipse to vsc!

Great job!

**Comment by robstryker** [comment]
Just curious, but, why are you still using an 11 year old runtime? There's been lots of improvements since 2008 ;)

**Comment by Swe77** [comment]
> Just curious, but, why are you still using an 11 year old runtime? There's been lots of improvements since 2008 ;)

Hi! Here is the story: this system integrates with other systems through an complex, in house made, SSO like integrator.
Also, it shares components (packages) with third a party system, resulting in a tightly coupled scenario. It is EJB 2x and has all those outdated patterns, and uses aged front end frameworks, what makes a migration quite challenging.

I hope migrate it as soon as possible.

**Comment by robstryker** [comment]
best of luck ;)

**Comment by Swe77** [comment]
> best of luck ;)

Thanks!

**Comment by robstryker** [comment]
Fixed and released. Re-open if anything doesn't work as expected.

**Comment by Swe77** [comment]
> Fixed and released. Re-open if anything doesn't work as expected.

Great! Thank you very much!
