### ISSUE TITLE
Output view steals focus

### ISSUE THREAD

**Issue by stimad** [redhat-developer/vscode-server-connector#473]
Hello there. I am not sure if this issue is directly related with vscode-server-connector, but I am interested if it is possible to disable behavior that output view steals focus when Wildfly server writes its output in it?

**Comment by ColinAckerley** [comment]
Same issue happens for me. Drives me insane because I will boot up (or even when I stop a server) a server and try to make some code changes while it boots. This is impossible to do because the cursor keeps jumping to the output window. Setting the vscodeAdapters.showChannelOnServerOutput: false option in the individual server settings and in the VSCode global settings has no effect. I would love for this issue to get fixed.

**Comment by odockal** [comment]
Hey. Thanks for reporting this, not quite nice behavior, I believe that we can do something about it.

**Comment by odockal** [comment]
To be just formally correct as of component where is should be fixed: https://github.com/redhat-developer/vscode-rsp-ui/issues/156.

**Comment by robstryker** [comment]
If you go to `File -> Preferences -> Settings` and search for `servers` you should see this setting:

```Vscode Adapters: Show Channel On Server Output
Show Server's output channel when new text added to output stream.```

You should be able to uncheck this setting.

**Comment by robstryker** [comment]
Closing since there is already a setting to override this behavior.
