### ISSUE TITLE
Create New Server -> Download Server -> Apache Tomcat 9.X ends with error

### ISSUE THREAD

**Issue by kalyankrishna1** [redhat-developer/vscode-server-connector#499]
_Unable to create the server: Extension backend error - failed to download runtime in time_

No other details are provided

**Comment by robstryker** [comment]
hrmm... i'm not able to replicate this.  

@odockal  let me know if you can just test it super quick?

**Comment by kalyankrishna1** [comment]
btw I am not blocked as figured out how to download one and use it instead. 

I trued using fiddler to see if there was something wrong with the internet, but that didn't had anything.

the extension has no logging or settings and that does not help either

**Comment by odockal** [comment]
@robstryker  @kalyankrishna1 I also can download all tomcat 9.x servers. Question here is, is it still occurring? If not, it might have been mirror outage, if it is still happening it might be intentional blocking of mirror site (unlikely) or something else. 
Would you mind to try it again?
You could probably debug the issue a bit by opening Developer Tools in VSCode and looking at Console tab for error or warnings.

**Comment by robstryker** [comment]
Closing as not replicatable. Please re-open if still occurring.
