### ISSUE TITLE
Does the extension no longer work for java 8?

### ISSUE THREAD

**Issue by kauanreisgomes** [redhat-developer/vscode-server-connector#572]
After release **0.26.0**, the extension Server Connector, Not working for **Java 8**. So i installed another version (**0.25.6**) and worked it.

Can someone explain the new updates to me?

Working on release 0.25.6

![image](https://user-images.githubusercontent.com/65663554/220915913-88e4856f-1f36-4c07-a79c-a03f114c2681.png)

Errors on release 0.26.1:

![image](https://user-images.githubusercontent.com/65663554/220916279-20e345a1-b62a-4805-aab3-6d6d624a5d87.png)

**Comment by robstryker** [comment]
We had issues in our build, specifically in the integration tests, that made running on Java 8 no longer acceptable for us. While admittedly, at the time, the core underlying RSP has no direct dependencies on Java 11, and with some work and reorganization we could have possibly found a way to separate out having the RSP use Java 8 but having the integration suite use Java 11, it simply wasn't possible this time due to constrained resources on my part. 

I made the decision to switch to Java 11, as well as update most of the UI indicating which java version is required to run the RSP. Java 8 is no longer receiving Active Support, and Java 11 is the preferred runtime now. 

Once I switched the build system to using Java 11, it became clear to me that if I accidentally slipped some Java 11 syntax into the codebase, I would not be aware of it and users would get unexplained errors. The safer option became to make Java 11 the new minimum runtime environment to use the RSP tooling. 

This doesn't mean you need to use Java 11 to launch your tomcat or other server types, as they can still be launched with lower java versions by overriding the 'vm.install.path' property in the server json for individual server definitions. But it does mean that Java 11 is required to launch the RSP now, and the RSP will be built and compiled with the java 11 class format. 

I realize this probably isn't the answer you wanted. Hopefully it doesn't cause you too much inconvenience.
