### ISSUE TITLE
port should be >= 0 and < 65536. received nan.

### ISSUE THREAD

**Issue by pilyong17** [redhat-developer/vscode-server-connector#576]
It was working fine until now, 
but I changed the project folder name and the server cannot be executed.
And the following message is output.

Even clearing the vscode cache and reinstalling it still the same.
What could be the cause?

* error message
Unable to start the server
	:  Extension backend error 
		- rsp error - community server connector failed to start 
		- port should be >= 0 and < 65536. received nan.

**Comment by robstryker** [comment]
This is very very strange. I've searched my git history in both vscode-server-connector and rsp-server-community, as well as vscode-rsp-ui, and can't find a string that fits that format anywhere.  

This incldues the current repository, the git history, even some dependencies like portFinder. 

I have abolutely no idea where such a string could be coming from.

**Comment by pilyong17** [comment]
I couldn't solve this problem. 
So, I decided to create a Tomcat execution script in task and use it.

**Comment by robstryker** [comment]
Can you tell me what version fo the extension you were using?

**Comment by olkornii** [comment]
@pilyong17 Hi, as I understand the problem is in "Community Server Connector", not "Red Hat Server Connector".
Community server connector is here: https://github.com/redhat-developer/rsp-server-community

Can I also ask you to provide more info about problem? Ideally, there would be steps to reproduce the problem. Something like that:
1. Create new <type/name> project
2. Install Community Server Connector
3. Create server <server_typ/version>
...

**Comment by robstryker** [comment]
We don't really allow the user to change ports manually for this thing, so, I mean, if you can install it and start and stop the RSP, those are all the steps I'd suggest testing for now.

**Comment by robstryker** [comment]
Unable to replicate. Please re-open if it occurs again.
