### ISSUE TITLE
Wildfly ports not accessible when running vscode in WSL

### ISSUE THREAD

**Issue by p-kager** [redhat-developer/vscode-server-connector#584]
Cannot access the wildfly ports from the host when using WSL. Everything else seems to be working fine, deployment etc.

Last version of this plugin that works is 0.25.6

**Comment by robstryker** [comment]
`Overriding the VM args and setting -Djava.net.preferIPv4Stack to true solved the issue.`

I'm very glad to hear that a workaround exists and we successfully discovered it. I will investigate why that flag changed and whether that was an intentional change for the given server type, or whether that was made in error. 

Thanks so much for your help in this issue.

**Comment by robstryker** [comment]
I'd mark this as a regression. Bad change in February 2023:

https://github.com/redhat-developer/rsp-server/commit/99aa3b140afa421e3098c45c2a41432c699e5a7f#diff-9f6d5aa9649f9d9cee49eecfbf6eb868749c251f7a9d09aad79cc5baba8e6bd5R53

When determining whether a host string is ipv4 or ipv6 we do some pattern matching, but it seems the only place we actually use this function is when we call it with the string `localhost` as the parameter. Thus, it's returning ipv6.

**Comment by robstryker** [comment]
No changes are planned here.
